name: monorepo_sample

packages:
  - packages/*
  - apps/*

scripts:
  analyze:
    exec: dart analyze .
  pub_get:
    exec: flutter pub get
  clean:
    exec: flutter clean
  test:
    exec: flutter test
