name: Build Apps

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    uses: ./.github/workflows/ci.yml

  build_web:
    name: ＠ Build web app
    runs-on: ubuntu-latest
    needs: static-checks
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
          channel: 'stable'
      - name: 🪄 Setup melos
        run: |
          flutter pub global activate melos 3.1.1
          melos bootstrap
      - name: ＠ Build web
        run: |
          cd apps/web_app
          flutter build web --release
      - name: 📦 Create deployment zip
        run: zip -r web_app.zip apps/web_app/build/web
      - name: 📤 Upload deployment zip
        uses: actions/upload-artifact@v3
        with:
          name: web_app.zip
          path: web_app.zip
