name: Build Apps

on:
  push:
    branches:
      - main
  pull:
    branches:
      - main

# Set permissions for GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  static-checks:
#    uses: ./.github/workflows/static-checks.yml

  build_web:
    name: ＠ Build web app
    runs-on: ubuntu-latest
#    needs: static-checks
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
          channel: 'stable'
      - name: 🪄 Setup melos
        run: |
          flutter pub global activate melos 3.1.1
          melos bootstrap
      - name: ＠ Build web
        run: |
          cd apps/web_app
          flutter build web --release
      - name: 📦 Create deployment zip
        run: zip -r web_app.zip apps/web_app/build/web
      - name: 📤 Upload deployment zip
        uses: actions/upload-artifact@v3
        with:
          name: web_app.zip
          path: web_app.zip

  deploy:
    name: 🚚 Deploy web app
    needs: build_web

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy web app
        uses: actions/deploy-pages@v2
        with:
          artifact_name: web_app.zip
